# Generated by Django 4.2.5 on 2023-09-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(default=None, max_length=255)),
                ('description', models.CharField(max_length=255, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=90)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media')),
            ],
            options={
                'db_table': 'Products',
            },
        ),
    ]
