# Generated by Django 4.2.5 on 2023-09-24 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(default=None, max_length=255)),
                ('description', models.CharField(max_length=255, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=90)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media')),
                ('sold_out', models.BooleanField(default=False)),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sold', models.IntegerField(default=0)),
                ('sale_price', models.IntegerField(default=0)),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new.product')),
            ],
        ),
        migrations.CreateModel(
            name='Loss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loss_name', models.CharField(default=None, max_length=255)),
                ('loss_amount', models.IntegerField(default=0)),
                ('loss_description', models.CharField(default=None, max_length=255)),
                ('loss_to_product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='new.product')),
            ],
        ),
    ]
