# Generated by Django 4.2.5 on 2023-09-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0003_product_sold_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='quantity_sold',
            field=models.IntegerField(),
        ),
    ]
