# Generated by Django 4.2.5 on 2023-09-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0004_alter_sale_quantity_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='quantity_sold',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_price',
            field=models.IntegerField(default=0),
        ),
    ]
