# Generated by Django 4.2.5 on 2023-09-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('product_description', models.CharField(max_length=255)),
                ('product_quantity', models.IntegerField()),
                ('product_image', models.ImageField(upload_to='media')),
            ],
            options={
                'db_table': 'Products',
            },
        ),
    ]
