# Generated by Django 4.2.6 on 2023-10-07 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='date',
            new_name='dateField',
        ),
    ]
