# Generated by Django 4.2.5 on 2023-09-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_gamezoneuser_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(choices=[('KE', 'Kenya'), ('TZ', 'Tanzania'), ('UGD', 'Uganda')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
